providers:
  kubernetesCRD:
    enabled: false

  kubernetesIngress:
    enabled: true
    ingressClass: okteto-traefik

rbac:
  enabled: false

serviceAccount:
  name: "default"

logs:
  access:
    enabled: true
