apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: okteto-read-ingress-class
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
